# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-06 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('UpdateUser', models.IntegerField(auto_created=True)),
                ('CreateUser', models.IntegerField(auto_created=True)),
                ('SysNo', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('Title', models.CharField(default='Title', max_length=50)),
                ('Content', models.TextField(null=True)),
                ('Status', models.BooleanField(default=True)),
                ('CreateTime', models.DateField(default=1488806791.470078)),
                ('UpdateTime', models.DateField()),
            ],
        ),
    ]
