# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-06 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='CreateTime',
            field=models.DateField(default='Mon Mar  6 21:40:21 2017'),
        ),
    ]
